spring:
  application:
    name: rabbitvps-server
  datasource:
    url: jdbc:h2:mem:rabbitvpsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  security:
    user:
      name: admin
      password: admin
  # 邮件配置
  mail:
    host: smtp.163.com
    username: rabbitvps@163.com
    password: FTgbv34HJxAgKimZ
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.163.com

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 0 # 永不过期

server:
  port: 8080

logging:
  level:
    com.rabbitvps: DEBUG

# 应用配置
app:
  base-url: "http://localhost:8080"

# 支付配置
payment:
  ezpay:
    pid: "1001"
    key: "89unJUB8HZ54Hj7x4nUj56HN4nUzUJ8i"
    submit-url: "https://ezfp.cn/submit.php"
    api-url: "https://ezfp.cn/mapi.php"
    notify-url: "http://localhost:8080/api/payment/notify"
    return-url: "http://localhost:3000/payment/return"