spring:
  application:
    name: rabbitvps-server
  datasource:
    url: jdbc:postgresql://my-postgresql.postgresql.svc.cluster.local:5432/vps
    driver-class-name: org.postgresql.Driver
    username: vps
    password: vps123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: ALWAYS
      data-locations: classpath:data.sql
  security:
    user:
      name: admin
      password: admin
  # 邮件配置
  mail:
    host: smtp.163.com
    username: rabbitvps@163.com
    password: FTgbv34HJxAgKimZ
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.163.com

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 0 # 永不过期

server:
  port: 8080

logging:
  level:
    com.rabbitvps: DEBUG

# 支付配置
payment:
  ezpay:
    pid: "4146"
    key: "ZOTFJ4JWGDD36ZJyQz3dWwJUBv3Jqq3r"
    submit-url: "https://ezfp.cn/submit.php"
    api-url: "https://ezfp.cn/mapi.php"
    notify-url: "https://rabbitvps.com/api/payment/notify"
    return-url: "https://rabbitvps.com/recharge"