apiVersion: v1
kind: Namespace
metadata:
  name: vps-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vps-server-config
  namespace: vps-server
data:
  application.yml: |
    spring:
      application:
        name: rabbitvps-server
      datasource:
        url: jdbc:postgresql://my-postgresql.postgresql.svc.cluster.local:5432/vps
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: vps123456

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        defer-datasource-initialization: true
      sql:
        init:
          mode: NEVER
          data-locations: classpath:data.sql
      security:
        user:
          name: admin
          password: admin

    # 启用健康检查端点
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        db:
          enabled: true
        mail:
          enabled: false  # 关闭邮件健康检查
      # 邮件配置
      mail:
        host: smtp.163.com
        username: rabbitvps@163.com
        password: FTgbv34HJxAgKimZ
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
              ssl:
                trust: smtp.163.com

    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 0 # 永不过期

    server:
      port: 8080

    logging:
      level:
        com.rabbitvps: DEBUG

    # 支付配置
    payment:
      ezpay:
        pid: "4146"
        key: "ZOTFJ4JWGDD36ZJyQz3dWwJUBv3Jqq3r"
        submit-url: "https://ezfp.cn/submit.php"
        api-url: "https://ezfp.cn/mapi.php"
        notify-url: "https://rabbitvps.com/api/payment/notify"
        return-url: "https://rabbitvps.com/recharge"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vps-server
  namespace: vps-server
  labels:
    app: vps-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vps-server
  template:
    metadata:
      labels:
        app: vps-server
    spec:
      containers:
      - name: vps-server
        image: ghcr.io/administrator/vps-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        # 启动探针 - 给应用充足的启动时间
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # 最多等待 5 分钟启动
        # 存活探针 - 检查应用是否需要重启
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 0  # startupProbe 成功后立即开始
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        # 就绪探针 - 检查应用是否准备好接收流量
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 0  # startupProbe 成功后立即开始
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "4Gi"
            cpu: "4000m"
          limits:
            memory: "8Gi"
            cpu: "8000m"
      volumes:
      - name: config-volume
        configMap:
          name: vps-server-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vps-server-service
  namespace: vps-server
  labels:
    app: vps-server
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: vps-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vps-server-ingress
  namespace: vps-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: vps-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vps-server-service
            port:
              number: 8080
