// 中文文本常量
export const TEXTS = {
  // 通用
  common: {
    confirm: '确认',
    cancel: '取消',
    save: '保存',
    delete: '删除',
    edit: '编辑',
    add: '添加',
    search: '搜索',
    loading: '加载中...',
    success: '操作成功',
    error: '操作失败',
    warning: '警告',
    info: '提示',
    yes: '是',
    no: '否',
    back: '返回',
    next: '下一步',
    previous: '上一步',
    submit: '提交',
    reset: '重置',
    refresh: '刷新',
    close: '关闭',
    open: '打开',
    view: '查看',
    download: '下载',
    upload: '上传',
    export: '导出',
    import: '导入',
    confirmDelete: '确认删除',
    actions: '操作',
    status: '状态',
    enabled: '启用',
    disabled: '禁用',
    active: '启用',
    inactive: '禁用',
    description: '描述',
    sortOrder: '排序',
    showing: '显示',
    of: '共',
    itemsPerPage: '每页显示',
    noData: '暂无数据',
    noSearchResults: '未找到匹配的结果',
    item: '项目',
    total: '总计'
  },

  // 导航菜单
  nav: {
    dashboard: '仪表盘',
    serverCategory: '服务器分类',
    serverGroup: '服务器组',
    servers: '服务器',
    priceGroups: '价格组',
    orders: '订单管理',
    transactions: '交易流水',
    sales: '销售页面',
    profile: '个人资料'
  },

  // 服务器类别管理
  serverCategory: {
    title: '服务器类别',
    name: '名称',
    deleteWarning: '删除服务器类别',
    confirmDelete: '确定要删除 {name} 类别吗？',
    loadFailed: '加载类别失败',
    saveFailed: '保存类别失败',
    deleteFailed: '删除类别失败'
  },

  // 服务器管理
  serverManage: {
    title: '服务器管理',
    serverInfo: '服务器信息',
    serverName: '服务器名称',
    status: '状态',
    operatingSystem: '操作系统',
    serverSpecs: '服务器配置',
    expiryDate: '到期时间',
    sshPort: 'SSH端口',
    powerManagement: '电源管理',
    powerDescription: '控制服务器的启动、重启和关闭操作',
    start: '启动',
    restart: '重启',
    stop: '关闭',
    passwordManagement: '密码管理',
    passwordDescription: '重置服务器root密码，新密码将立即生效',
    newPassword: '新密码',
    resetPassword: '重置密码',
    generatePassword: '生成随机密码',
    systemMonitoring: '系统监控',
    cpuUsage: 'CPU使用率',
    memoryUsage: '内存使用率',
    diskUsage: '磁盘使用率',
    noSystemInfo: '暂无系统信息',
    networkInfo: '网络信息',
    ipAddress: 'IP地址',
    bandwidth: '带宽',
    sshAccess: 'SSH访问',
    connectSSH: '连接SSH',
    confirmStart: '确认启动',
    confirmStartDescription: '确定要启动这台服务器吗？',
    confirmRestart: '确认重启',
    confirmRestartDescription: '确定要重启这台服务器吗？服务器将会短暂中断服务。',
    confirmStop: '确认关闭',
    confirmStopDescription: '确定要关闭这台服务器吗？关闭后需要手动启动。',
    confirmResetPassword: '确认重置密码',
    confirmResetPasswordDescription: '确定要重置服务器密码吗？新密码将立即生效。'
  },

  // 订单状态
  orderStatus: {
    pending: '待处理',
    paid: '已支付',
    cancelled: '已取消',
    expired: '已过期'
  },

  // 表单验证
  validation: {
    required: '此字段为必填项',
    email: '请输入有效的邮箱地址',
    minLength: '最少需要 {min} 个字符',
    maxLength: '最多允许 {max} 个字符',
    numeric: '请输入数字',
    phone: '请输入有效的手机号码',
    url: '请输入有效的URL地址',
    ip: '请输入有效的IP地址',
    invalidIp: '请输入有效的IP地址格式',
    invalidIP: '请输入有效的IP地址格式',
    port: '端口号范围应在 1-65535 之间'
  },

  // 主题设置
  theme: {
    title: '主题设置',
    subtitle: '个性化您的界面外观',
    light: '浅色',
    dark: '深色',
    auto: '自动',
    displayMode: '显示模式',
    themeColors: '主题配色',
    primaryColor: '主色调',
    secondaryColor: '辅助色',
    accentColor: '强调色',
    customTheme: '自定义主题',
    presets: {
      default: '默认',
      blue: '蓝色',
      green: '绿色',
      purple: '紫色',
      red: '红色',
      orange: '橙色',
      teal: '青色',
      indigo: '靛蓝',
      pink: '粉色',
      amber: '琥珀'
    }
  },

  // 页脚
  footer: {
    company: 'RabbitVPS 管理系统',
    poweredBy: '由 RabbitVPS 提供技术支持',
    privacy: '隐私政策',
    terms: '服务条款',
    support: '技术支持'
  },

  // 认证相关
  auth: {
    login: {
      title: '欢迎回来',
      subtitle: '请登录您的账户',
      username: '用户名',
      password: '密码',
      loginButton: '立即登录',
      loginButtonLoading: '登录中...',
      noAccount: '还没有账号？',
      registerLink: '立即注册',
      forgotPassword: '忘记密码？'
    },
    register: {
      title: '加入我们',
      subtitle: '创建您的新账户',
      username: '用户名',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      registerButton: '立即注册',
      registerButtonLoading: '注册中...',
      hasAccount: '已有账号？',
      loginLink: '立即登录',
      passwordStrength: '密码强度',
      passwordWeak: '弱',
      passwordMedium: '中等',
      passwordStrong: '强'
    },
    errors: {
      emptyFields: '用户名和密码不能为空',
      allFieldsRequired: '所有字段都不能为空',
      pleaseFixErrors: '请修正表单中的错误后再提交',
      passwordMismatch: '两次输入的密码不一致',
      invalidCredentials: '用户名或密码错误',
      userExists: '用户已存在',
      networkError: '网络连接错误',
      serverError: '服务器错误，请稍后重试'
    }
  },

  // 仪表板
  dashboard: {
    welcome: '欢迎回来，{username}！',
    subtitle: '这里是您的个人仪表板',
    onlineStatus: '在线状态',
    userInfo: '用户信息',
    username: '用户名',
    email: '邮箱',
    quickNavigation: '快速导航',
    profileDescription: '个人资料和账户设置',
    tokenStatus: 'Token状态',
    tokenValid: '有效（永不过期）',
    systemFeatures: '系统功能',
    jwtAuth: 'JWT认证已启用',
    tokenNeverExpires: 'Token永不过期',
    h2Database: 'H2数据库存储',
    passwordEncryption: '安全的密码加密',
    enabled: '启用'
  },

  // 用户资料
  profile: {
    title: '个人资料',
    basicInfo: '基本信息',
    username: '用户名',
    email: '邮箱',
    memberSince: '注册时间',
    changePassword: '修改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmNewPassword: '确认新密码',
    saveChanges: '保存修改'
  },

  // 忘记密码
  forgotPassword: {
    title: '忘记密码',
    subtitle: '输入您的邮箱地址，我们将发送验证码',
    email: '邮箱地址',
    sendCode: '发送验证码',
    sendingCode: '发送中...',
    verificationCode: '验证码',
    newPassword: '新密码',
    confirmPassword: '确认新密码',
    resetPassword: '重置密码',
    resetting: '重置中...',
    backToEmail: '返回',
    backToLogin: '返回登录',
    rememberPassword: '想起密码了？',
    codeSent: '验证码已发送到您的邮箱',
    codeResent: '验证码已重新发送',
    codeInfo: '验证码已发送到 {email}，请查收邮件',
    codeFormat: '验证码必须是6位数字',
    resendCode: '重新发送验证码',
    resendCountdown: '重新发送 ({seconds}s)',
    resetSuccess: '密码重置成功，即将跳转到登录页面',
    sendCodeError: '发送验证码失败',
    resetError: '密码重置失败'
  },

  // 价格组管理
  priceGroup: {
    title: '价格组管理',
    add: '添加价格组',
    list: '价格组列表',
    searchPlaceholder: '搜索价格组...',
    name: '名称',
    description: '描述',
    sortOrder: '排序',
    hour: '小时',
    day: '天',
    month: '月',
    quarter: '季度',
    halfYear: '半年',
    year: '年',
    priceUnit: '¥',
    hourlyPrice: '小时价格',
    dailyPrice: '日价格',
    monthlyPrice: '月价格',
    quarterlyPrice: '季度价格',
    semiAnnualPrice: '半年价格',
    annualPrice: '年价格',
    serverGroup: '服务器组',
    salesPageHtml: '销售页面HTML',
    salesPageHtmlPlaceholder: '输入销售页面的HTML代码...',
    salesPagePreview: '销售页面预览',
    preview: '预览',
    active: '启用',
    inactive: '禁用',
    noServerGroup: '未关联服务器组',
    noSalesPage: '未设置销售页面',
    addDialog: '添加价格组',
    editDialog: '编辑价格组',
    deleteWarning: '删除价格组',
    confirmDelete: '确定要删除 {name} 吗？',
    required: '此字段为必填项',
    positiveNumber: '必须是正数',
    nonNegativeNumber: '必须是非负数',
    loadError: '加载价格组失败',
    saveError: '保存价格组失败',
    deleteError: '删除价格组失败',
    createSuccess: '创建价格组成功',
    updateSuccess: '更新价格组成功',
    deleteSuccess: '删除价格组成功',
    prices: '价格配置'
  },

  // 销售页面
  sales: {
    priceGroup: '价格组',
    noDescription: '暂无描述',
    configureParameters: '配置参数',
    customizeServerConfig: '自定义服务器配置',
    configLocked: '配置已锁定',
    cpu: 'CPU',
    cores: '核',
    memory: '内存',
    gb: 'GB',
    storage: '存储',
    ssd: 'SSD',
    bandwidth: '带宽',
    mbps: 'Mbps',
    ipCount: 'IP数量',
    osSelection: '操作系统选择',
    selectOS: '选择操作系统',
    systemName: '系统名称',
    selectVersion: '选择版本',
    version: '版本',
    selected: '已选择',
    initialPassword: '初始密码',
    serverInitialPassword: '服务器初始密码',
    enterInitialPassword: '请输入初始密码',
    sshPort: 'SSH端口',
    sshPortNumber: 'SSH端口号',
    enterPortNumber: '请输入端口号',
    autoRenewal: '自动续费',
    autoRenewalDesc: '到期前自动续费，避免服务中断',
    currentConfig: '当前配置',
    hardwareSpecs: '硬件规格',
    networkConfig: '网络配置',
    softwareConfig: '软件配置',
    billingConfig: '计费配置',
    ipAddress: 'IP地址',
    operatingSystem: '操作系统',
    password: '密码',
    billingCycle: '计费周期',
    totalPrice: '总价格',
    priceBreakdown: '价格明细',
    basePrice: '基础价格',
    configPrice: '配置价格',
    discount: '折扣',
    finalPrice: '最终价格',
    addToCart: '加入购物车',
    buyNow: '立即购买',
    outOfStock: '暂时缺货',
    comingSoon: '即将上线',
    systemConfig: '系统配置',
    pricingPlans: '价格方案',
    save: '节省',
    noPriceInfo: '暂无价格信息',
    processing: '处理中...',
    purchaseNow: '立即购买',
    selectPricePlan: '请选择价格方案',
    selectPriceFirst: '请先选择价格方案',
    orderCreatedSuccess: '订单创建成功',
    noProducts: '暂无产品',
    noProductsHint: '当前没有可用的产品，请联系我们了解更多信息',
    contactUs: '联系我们',
    count: '个',
    hourly: '按小时',
    daily: '按天',
    monthly: '按月',
    quarterly: '按季度',
    semiAnnual: '半年',
    annual: '按年',
    perHour: '/小时',
    perDay: '/天',
    perMonth: '/月',
    perQuarter: '/季度',
    perSemiAnnual: '/半年',
    perYear: '/年'
  },

  // 服务器分组
  groups: {
    title: '服务器分组',
    groupName: '分组名称',
    selectCategory: '选择类别',
    region: '地区',
    country: '国家',
    city: '城市',
    uncategorized: '未分类',
    deleteWarning: '删除分组',
    confirmDelete: '确定要删除分组 "{name}" 吗？此操作不可撤销。'
  },

  // 交易记录
  transaction: {
    title: '交易记录',
    searchPlaceholder: '搜索交易记录...',
    type: '交易类型',
    status: '状态',
    totalIncome: '总收入',
    totalExpense: '总支出',
    totalTransactions: '总交易数',
    pendingTransactions: '待处理交易',
    list: '交易列表',
    before: '变更前',
    after: '变更后',
    noTransactions: '暂无交易记录',
    noTransactionsDesc: '当前没有任何交易记录',
    transactionNumber: '交易号',
    amount: '金额',
    balanceChange: '余额变动',
    balanceBefore: '变更前余额',
    balanceAfter: '变更后余额',
    description: '描述',
    relatedOrder: '关联订单',
    paymentMethod: '支付方式',
    createdAt: '创建时间',
    completedAt: '完成时间',
    typeRecharge: '充值',
    typeOrderPayment: '订单支付',
    typeRefund: '退款',
    typeWithdrawal: '提现',
    typeAdjustment: '调整',
    statusPending: '待处理',
    statusProcessing: '处理中',
    statusCompleted: '已完成',
    statusFailed: '失败',
    statusCancelled: '已取消',
    transactionDetails: '交易详情'
  },

  // 订单管理
  order: {
    list: '订单列表',
    noOrders: '暂无订单',
    noOrdersDesc: '当前没有任何订单记录',
    orderNumber: '订单号',
    status: '状态',
    amount: '金额',
    billingPeriod: '计费周期',
    serverName: '服务器名称',
    createdAt: '创建时间',
    expiresAt: '到期时间',
    serverSpecs: '服务器配置',
    cores: '核',
    memory: '内存',
    storage: '存储',
    bandwidth: '带宽',
    manageServer: '管理服务器',
    statusPending: '待处理',
    statusPaid: '已支付',
    statusProcessing: '处理中',
    statusActive: '活跃',
    statusSuspended: '已暂停',
    statusCancelled: '已取消',
    statusExpired: '已过期',
    hourly: '按小时',
    daily: '按天',
    monthly: '按月',
    quarterly: '按季度',
    semiAnnual: '半年',
    annual: '按年',
    title: '订单管理',
    searchPlaceholder: '搜索订单...',
    orderDetails: '订单详情'
  },

  // 支付记录
  payment: {
    title: '支付记录',
    list: '支付记录列表',
    searchPlaceholder: '搜索支付记录...',
    orderNumber: '订单号',
    amount: '支付金额',
    paymentMethod: '支付方式',
    status: '支付状态',
    productName: '商品名称',
    createdAt: '创建时间',
    completedAt: '完成时间',
    thirdPartyOrderNo: '第三方订单号',
    clientIp: '客户端IP',
    device: '设备信息',
    paymentDetails: '支付详情',
    checkStatus: '检查状态',
    
    // 状态
    statusPending: '待支付',
    statusSuccess: '支付成功',
    statusFailed: '支付失败',
    statusCancelled: '已取消',
    
    // 统计
    successfulPayments: '成功支付',
    pendingPayments: '待支付',
    failedPayments: '失败支付',
    totalPayments: '总支付数',
    
    // 空状态
    noPayments: '暂无支付记录',
    noPaymentsDesc: '您还没有任何支付记录'
  }
}

// 辅助函数：替换文本中的参数
export function formatText(text: string, params: Record<string, any> = {}): string {
  return text.replace(/\{(\w+)\}/g, (match, key) => {
    return params[key] !== undefined ? String(params[key]) : match
  })
}


